package game;
// Item class file
public class Item{
	// Variables
	private int itemId;
	private String description;
	private int weight;
	private int damage;
	private int health;
	private int quest_id;
	private int value;
	
	// Constructor
	public Item(String d, int w, int dmg, int h, int q, int v) {
		description = d;
		weight = w;
		damage = dmg;
		health = h;
		quest_id = q;
		value = v;
	}
	
	public Item getItem(int id){
		return null;
	}
	
	public int getId(){
		return itemId;
	}
	
	public void setId(int i){
		itemId = i;
	}
	
	// Returns description of item
	public String getDescription() {
		return description;
	}
	
	// Sets a new description
	public void setDescription(String d) {
		this.description = d;
	}
	
	// Returns weight of item
	public int getWeight() {
		return weight;
	}
	
	// Sets weight of item
	public void setWeight(int w) {
		this.weight = w;
	}
	
	// Gets damage of item
	public int getDamage() {
		return damage;
	}
	
	// Sets the damage of item
	public void setDamage(int d) {
		this.damage = d;
	}
	
	// Gets the amount of health regenerated by item
	public int getHealth() {
		return health;
	}
	
	// Sets the amount of health regenerated by item
	public void setHealth(int h) {
		this.health = h;
	}
	
	// Gets the quest id of item
	public int getQuestId() {
		return quest_id;
	}
	
	// Sets the quest id of item 
	public void setQuestId(int q) {
		this.quest_id = q;
	}
	
	// Gets the treasure value of item
	public int getValue() {
		return value;
	}
	
	// Sets the treasure value of item 
	public void setValue(int v) {
		this.value = v;
	}
}