package ycp.edu.cs320.adventure.game;
// Item class file
public class Item{
	// Variables
	private int gameId;
	private int itemId;
	private int inventoryId;
	private String description;
	private String name;
	private int weight;
	private int damage;
	private int health;
	private int quest_id;
	private int value;
	
	// Parameterless Constructor
	public Item() {
		
	}
	
	// Constructor
	public Item(String n, String d, int g, int i, int w, int dmg, int h, int q, int v) {
		name = n;
		description = d;
		gameId = g;
		itemId = i;
		weight = w;
		damage = dmg;
		health = h;
		quest_id = q;
		value = v;
	}
	

	public int getGameId(){
		return gameId;
	}
	public void setGameId(int i){
		gameId = i;
	}
	
	public int getItemId(){
		return itemId;
	}
	public void setItemId(int i){
		itemId = i;
	}
	
	public int getInventoryId(){
		return inventoryId;
	}
	public void setInventoryId(int i){
		inventoryId = i;
	}
	
	public String getName() {
		return name;
	}
	public void setName(String n) {
		name = n;
	}
	
	// Returns description of item
	public String getDescription() {
		return description;
	}
	
	// Sets a new description
	public void setDescription(String d) {
		this.description = d;
	}
	
	// Returns weight of item
	public int getWeight() {
		return weight;
	}
	
	// Sets weight of item
	public void setWeight(int w) {
		this.weight = w;
	}
	
	// Gets damage of item
	public int getDamage() {
		return damage;
	}
	
	// Sets the damage of item
	public void setDamage(int d) {
		this.damage = d;
	}
	
	// Gets the amount of health regenerated by item
	public int getHealth() {
		return health;
	}
	
	// Sets the amount of health regenerated by item
	public void setHealth(int h) {
		this.health = h;
	}
	
	// Gets the quest id of item
	public int getQuestId() {
		return quest_id;
	}
	
	// Sets the quest id of item 
	public void setQuestId(int q) {
		this.quest_id = q;
	}
	
	// Gets the treasure value of item
	public int getValue() {
		return value;
	}
	
	// Sets the treasure value of item 
	public void setValue(int v) {
		this.value = v;
	}
}
